version: 2.1

orbs:
  docker: ledger/docker@volatile

workflows:
  build_test_and_publish:
    jobs:
      - docker/build_image:
          docker_login: true
          filters:
            tags:
              only: /.*/
      - docker/test_image:
          dgoss_docker_env_vars: |-
            DSENSE_GATEWAY_SERVER_HOST=0.0.0.0
            DSENSE_GATEWAY_SERVER_PORT=8000
            DSENSE_GATEWAY_SERVER_PATH=/
            DSENSE_GATEWAY_DATABASE_TYPE=h2
            DSENSE_GATEWAY_DATABASE_DRIVER=org.h2.Driver
            DSENSE_GATEWAY_DATABASE_URL=jdbc:h2:mem:countervalue-service;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
            DSENSE_GATEWAY_DATABASE_USER=sa
            DSENSE_GATEWAY_DATABASE_PASSWORD=
            DSENSE_GATEWAY_DATABASE_SCHEMA=db
            DSENSE_GATEWAY_SMART_CONTRACT_ADDRESS=0xDFb287530FD4c1e59456DE82a84e4aae7C250Ec1
            DSENSE_GATEWAY_SMART_CONTRACT_METHOD=setData
            DSENSE_GATEWAY_CHAIN_ID=401697
            DSENSE_GATEWAY_GAS_LIMIT=100000
            DSENSE_GATEWAY_HTTP_PROVIDER=https://rpc.slock.it/tobalaba
          requires:
            - docker/build_image
          filters:
            tags:
              only: /.*/
      - docker/publish_image:
          requires:
            - docker/test_image
          filters:
            branches:
              only:
                - develop
                - release_candidate
                - master
            tags:
              only: /.*/
